# PlotVP

In [ ]:
from users360 import *
PlotVP(trace=[1, 0, 0]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
PlotVP(trace=[-1, 0, 0]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
PlotVP(trace=[0, 1, 0]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
PlotVP(trace=[0, -1, 0]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
PlotVP(trace=[0, 0, 1]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
PlotVP(trace=[0, 0, -1]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)

In [ ]:
from users360 import *
onevp = PlotVP(Dataset.singleton().one_trace())
onevp.show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
onevp.show(VPEXTRACT_VORO_14_CENTER, to_html=False)

# PlotTraces

In [ ]:
from users360 import *
one_user = PlotTraces(Dataset.singleton().traces_video_user())
one_user.show(VPEXTRACT_RECT_4_6_CENTER)
one_user.show(VPEXTRACT_VORO_14_CENTER)

In [ ]:
from users360 import *
all_users = PlotTraces(Dataset.singleton().traces_video())
all_users.show(VPEXTRACT_RECT_4_6_CENTER)
all_users.show(VPEXTRACT_VORO_14_CENTER)


In [ ]:
from users360 import *
some_traces = PlotTraces(Dataset.singleton().traces_video_user(0.1))
some_traces.show(VPEXTRACT_RECT_4_6_CENTER)
some_traces.show(VPEXTRACT_VORO_14_CENTER)

# PlotTraces users by entropy

In [ ]:
from users360 import *
dataset = Dataset.singleton()
# dataset.users_entropy(VPEXTRACT_RECT_4_6_CENTER, plot_scatter=True)
# dataset.users_entropy(VPEXTRACT_RECT_8_6_CENTER, plot_scatter=True)
dataset.users_entropy(VPEXTRACT_VORO_14_CENTER, plot_scatter=True)
# dataset.dump()


In [ ]:
from users360 import *
dataset = Dataset.singleton()
users_hight = dataset.users_hight[:]
users_low = dataset.users_low[:]
PlotTraces(dataset.traces_video(users_hight), title_sufix="entropy_hight").show(VPEXTRACT_RECT_4_6_CENTER)
PlotTraces(dataset.traces_video(users_low), title_sufix="entropy_low").show(VPEXTRACT_RECT_4_6_CENTER)

In [ ]:
from users360 import *
dataset = Dataset.singleton()
# users_hight = dataset.users_hight[:3]
# users_low = dataset.users_low[:3]
users_hight = dataset.users_hight[:]
users_low = dataset.users_low[:]
dataset.metrics_vpextract_video([VPEXTRACT_RECT_4_6_CENTER, VPEXTRACT_VORO_14_CENTER], users=users_hight)
dataset.metrics_vpextract_video([VPEXTRACT_RECT_4_6_CENTER, VPEXTRACT_VORO_14_CENTER], users=users_low)

# PlotTraces users by region

In [ ]:
from users360 import *
dataset = Dataset.singleton()
users_polar = PlotTraces(dataset.traces_video_poles()[:], title_sufix="poles")
users_polar.show(VPEXTRACT_RECT_4_6_CENTER)
users_equator = PlotTraces(dataset.traces_video_equator()[:], title_sufix="equator")
users_equator.show(VPEXTRACT_RECT_4_6_CENTER)

In [ ]:
# from users360 import *
# dataset = Dataset.singleton()
# users_polar.metrics_vpextract([VPEXTRACT_RECT_4_6_CENTER, VPEXTRACT_VORO_14_CENTER])
# users_equator.metrics_vpextract([VPEXTRACT_RECT_4_6_CENTER, VPEXTRACT_VORO_14_CENTER])

# Dataset metrics VP

In [ ]:
from users360 import *
dataset = Dataset.singleton()
dataset.met_vpext = None # force recalculate
dataset.metrics_vpextract_video(VPEXTRACT_METHODS, users=['0', '1', '2'], perc_traces=0.1)
# dataset.singleton_dump()


In [ ]:

from users360 import *
from numpy import array as array
# PlotVP(trace=[0.5624332, 0.4141108, -0.687445454]).show(VPEXTRACT_RECT_4_6_CENTER, to_html=False)
# PlotVP(trace=[-0.56643968,  0.55032895,  0.61342002]).show(VPEXTRACT_RECT_4_6_CENTER)
# PlotVP(trace=[ 0.0438392 ,  0.74582096,  0.66470235]).show(VPEXTRACT_RECT_4_6_CENTER)
# PlotVP(trace=[ 0.86167495,  0.37456039,  0.34237524]).show(VPEXTRACT_RECT_4_6_CENTER)
# VPEXTRACT_RECT_4_6_CENTER.request(trace=[-0.56643968,  0.55032895,  0.61342002],return_metrics=True)
# VPEXTRACT_RECT_4_6_CENTER.request(trace=[ 0.0438392 ,  0.74582096,  0.66470235],return_metrics=True)
# VPEXTRACT_RECT_4_6_CENTER.request(trace=[ 0.86167495,  0.37456039,  0.34237524],return_metrics=True)

plot = PlotPolygon(VPEXTRACT_RECT_4_6_CENTER)
t_ver, t_hor = 6 , 4

bad_traces = [
    array([ 0.01950938, -0.99865077,  0.04812503]),
    array([ 0.0438392,   0.74582096,  0.66470235]),
    array([ 0.35368315, -0.93035827, -0.0966526 ]),
    array([ 0.52100603, -0.85336471,  0.01792752]),
    array([ 0.54567701, -0.8345146 , -0.07630191]),
    array([ 0.79732921, -0.59556031, -0.09784705]),
    array([ 0.81414446, -0.58059996,  0.00851362]),
    array([ 0.86167495,  0.37456039,  0.34237524]),
    array([ 0.94371971, -0.29295564, -0.15352554]),
    array([ 0.9953681 ,  0.00500964, -0.09600647]),
    array([ 0.99627636, -0.06573347, -0.05578992]),
    array([ 0.99948643, -0.02040683, -0.0247072 ]),
    array([-0.1215687 , -0.99141498,  0.04813923]),
    array([-0.23741683, -0.97052729, -0.04135241]),
    array([-0.40910286,  0.88842715, -0.20816349]),
    array([-0.48071625, -0.87682852,  0.00914523]),
    array([-0.56643968,  0.55032895,  0.61342002]),
    array([-0.64191121, -0.76602483, -0.03399935]),
    array([-0.81942645,  0.54278193, -0.18419573]),
    array([-0.84946775,  0.51344432, -0.12157085]),
    array([-0.88987281, -0.45615206,  0.0071886 ]),
    array([-0.89009305, -0.43712466, -0.12905967]),
    array([-0.9471813 ,  0.29678096, -0.12152634]),
    array([-0.99594966, -0.08781552,  0.01930554]),
    array([-0.99956943, -0.01570768, -0.02478355]),
]

for trace in bad_traces:
    for row in range(1,t_ver): # range(t_ver):
        for col in range(t_hor):
            print(f"-- row={row},col={col}")
            tile_poly_rc = polygon.SphericalPolygon(tile_points(t_ver, t_hor, row, col))
            fov_poly_trace = polygon.SphericalPolygon(fov_points(trace))
            print("tile_poly_rc.area={}".format(tile_poly_rc.area()))
            print("fov_poly_trace.area={}".format(fov_poly_trace.area()))
            print("overlap_ratio={}".format(tile_poly_rc.overlap(fov_poly_trace)))
            print("lost_ratio={}".format(1-tile_poly_rc.overlap(fov_poly_trace)))
            tile_poly_rc = tile_poly(t_ver, t_hor, row, col)
            fov_poly_trace = fov_poly(trace)
            print("tile_poly_rc.area={}".format(tile_poly_rc.area()))
            print("fov_poly_trace.area={}".format(fov_poly_trace.area()))
            print("overlap_ratio={}".format(tile_poly_rc.overlap(fov_poly_trace)))
            print("lost_ratio={}".format(1-tile_poly_rc.overlap(fov_poly_trace)))
